### ISSUE TITLE
No URLMap entries found in application configuration on new php72 runtime (standard)

### ISSUE THREAD

**Issue by pierrefaure** [NYTimes/drone-gae#39]
php 7.2 is now available on App Engine standard: https://cloud.google.com/appengine/docs/standard/php7/config/appref#handlers_element

I wanted to implement it for our apps as it would reduce our costs compared to a `flexible` environment.

Here's my `app.test.yaml`: 
```yaml
# Default GCloud App Engine deployment settings
runtime: php72

service: service-test

instance_class: B1
manual_scaling:
  instances: 1

env_variables:
  ENV: 'my env vars'

# GCloud DB settings
beta_settings:
  cloud_sql_instances: 'project:localization:service'
```

When using `gcloud app deploy app.test.yaml --project=project` my service works well.

But when using the drone plugin it crashes saying:
```
ERROR: (gcloud.app.deploy) An error occurred while parsing file: [/drone/src/bitbucket.org/mylocalname/service/app.yaml]
No URLMap entries found in application configuration
  in "/drone/src/bitbucket.org/mylocalname/service/app.yaml"
```

Here's the part responsible of the deploy in my `.drone.yml`: 
```
deploy-test:
    image: nytimes/drone-gae
    action: deploy
    project: project
    app_file: app.test.yaml
    version: ${DRONE_BUILD_NUMBER}
    secrets:
      - source: GAE_CREDENTIALS_TEST
        target: GAE_CREDENTIALS
    when:
      event: deployment
      environment: test
```

First thing I found weird was that it seems to point to `app.yaml` in the error message although my file name is `app.test.yaml`. Renaming it didn't solve the issue and after checking it was working with a php runtime and flexible environment (pointing to `app.yaml` but the file was also named differently) so I believe this is not the issue.

I'm a bit lost and my knowledge is limited in Go. 
Is it that it's new and not well interpreted by the plugin yet or am I missing something?
